from __future__ import annotations

CONTENT_FRAMEWORK_VERSION = "0.1.0"
CONTENT_ITEM_CONTRACT_VERSION = "1.0"
CONTENT_REVISION_CONTRACT_VERSION = "1.0"
CHANNEL_CONTENT_VARIANT_CONTRACT_VERSION = "1.0"
CONTENT_REQUIREMENTS_CONTRACT_VERSION = "1.0"
PUBLICATION_PLAN_CONTRACT_VERSION = "1.0"
PUBLICATION_TARGET_CONTRACT_VERSION = "1.0"
