"""Contract versions for host-owned certification signers."""

TRUSTED_SIGNER_FRAMEWORK_VERSION = "0.1.0"
HOST_SIGNER_CONTRACT_VERSION = "1.0"
SIGNER_ENROLLMENT_CONTRACT_VERSION = "1.0"
SIGNER_ROTATION_CONTRACT_VERSION = "1.0"

__all__ = [
    "HOST_SIGNER_CONTRACT_VERSION",
    "SIGNER_ENROLLMENT_CONTRACT_VERSION",
    "SIGNER_ROTATION_CONTRACT_VERSION",
    "TRUSTED_SIGNER_FRAMEWORK_VERSION",
]
