"""Contract constants for the Markdown Website channel plugin v0.1."""

MARKDOWN_WEBSITE_PLUGIN_VERSION = "0.1.0"
OWNED_PUBLICATION_METADATA_CONTRACT_VERSION = "1.0"
MARKDOWN_RENDERING_CONTRACT_VERSION = "1.0"
WEBSITE_PUBLICATION_PROFILE_CONTRACT_VERSION = "1.0"
WEBSITE_PUBLICATION_VERIFICATION_CONTRACT_VERSION = "1.0"
PUBLICATION_DEPENDENCY_CONTRACT_VERSION = "1.0"
PUBLICATION_LINK_ATTRIBUTION_CONTRACT_VERSION = "1.0"

PLUGIN_ID = "channel.markdown_website"
CHANNEL_FAMILY_OWNED_PUBLICATION = "owned_publication"
CHANNEL_FAMILY_SOCIAL_DISTRIBUTION = "social_distribution"
PUBLICATION_FORMAT_MARKDOWN = "markdown"
EXECUTION_MODE_BUILT_IN = "built_in_in_process"
PUBLISHER_TYPE_GIT_REPOSITORY = "git_repository"

__all__ = [
    "CHANNEL_FAMILY_OWNED_PUBLICATION",
    "CHANNEL_FAMILY_SOCIAL_DISTRIBUTION",
    "EXECUTION_MODE_BUILT_IN",
    "MARKDOWN_RENDERING_CONTRACT_VERSION",
    "MARKDOWN_WEBSITE_PLUGIN_VERSION",
    "OWNED_PUBLICATION_METADATA_CONTRACT_VERSION",
    "PLUGIN_ID",
    "PUBLICATION_DEPENDENCY_CONTRACT_VERSION",
    "PUBLICATION_FORMAT_MARKDOWN",
    "PUBLICATION_LINK_ATTRIBUTION_CONTRACT_VERSION",
    "PUBLISHER_TYPE_GIT_REPOSITORY",
    "WEBSITE_PUBLICATION_PROFILE_CONTRACT_VERSION",
    "WEBSITE_PUBLICATION_VERIFICATION_CONTRACT_VERSION",
]
