from __future__ import annotations

EXECUTION_FRAMEWORK_VERSION = "0.1.0"
PUBLICATION_DISPATCHER_CONTRACT_VERSION = "1.0"
EXECUTION_ATTEMPT_CONTRACT_VERSION = "1.0"
EXECUTION_LEASE_CONTRACT_VERSION = "1.0"
EXECUTION_RECONCILIATION_CONTRACT_VERSION = "1.0"
EXECUTION_RETRY_POLICY_CONTRACT_VERSION = "1.0"
