"""Plugin Distribution Framework contract versions."""

PLUGIN_DISTRIBUTION_FRAMEWORK_VERSION = "0.1.0"
PLUGIN_PACKAGE_CONTRACT_VERSION = "1.0"
PLUGIN_RELEASE_METADATA_CONTRACT_VERSION = "1.0"
PLUGIN_SIGNATURE_POLICY_CONTRACT_VERSION = "1.0"
PLUGIN_REGISTRY_CONTRACT_VERSION = "1.0"
PLUGIN_INSTALLATION_CONTRACT_VERSION = "1.0"
PLUGIN_ACTIVATION_CONTRACT_VERSION = "1.0"
PLUGIN_UPDATE_CONTRACT_VERSION = "1.0"
PLUGIN_ENTRY_POINT_GROUP = "social_media_manager.plugins"
PLUGIN_INSTALLER_NAME = "socialmediamanager-plugin-installer"

__all__ = [
    "PLUGIN_ACTIVATION_CONTRACT_VERSION",
    "PLUGIN_DISTRIBUTION_FRAMEWORK_VERSION",
    "PLUGIN_ENTRY_POINT_GROUP",
    "PLUGIN_INSTALLATION_CONTRACT_VERSION",
    "PLUGIN_INSTALLER_NAME",
    "PLUGIN_PACKAGE_CONTRACT_VERSION",
    "PLUGIN_REGISTRY_CONTRACT_VERSION",
    "PLUGIN_RELEASE_METADATA_CONTRACT_VERSION",
    "PLUGIN_SIGNATURE_POLICY_CONTRACT_VERSION",
    "PLUGIN_UPDATE_CONTRACT_VERSION",
]
