"""Alpha onboarding v0.1 framework."""

from .contracts import (
    ALPHA_DEMO_MODE_CONTRACT_VERSION,
    ALPHA_FIRST_PUBLICATION_CONTRACT_VERSION,
    ALPHA_GUIDED_RECOVERY_CONTRACT_VERSION,
    ALPHA_ONBOARDING_FRAMEWORK_VERSION,
    ALPHA_ONBOARDING_SESSION_CONTRACT_VERSION,
    ALPHA_ONBOARDING_STEP_CONTRACT_VERSION,
    ALPHA_SETUP_READINESS_CONTRACT_VERSION,
)
from .service import AlphaOnboardingService

__all__ = [
    "ALPHA_DEMO_MODE_CONTRACT_VERSION",
    "ALPHA_FIRST_PUBLICATION_CONTRACT_VERSION",
    "ALPHA_GUIDED_RECOVERY_CONTRACT_VERSION",
    "ALPHA_ONBOARDING_FRAMEWORK_VERSION",
    "ALPHA_ONBOARDING_SESSION_CONTRACT_VERSION",
    "ALPHA_ONBOARDING_STEP_CONTRACT_VERSION",
    "ALPHA_SETUP_READINESS_CONTRACT_VERSION",
    "AlphaOnboardingService",
]
