"""Certification evidence trust contract versions."""

from __future__ import annotations

CERTIFICATION_EVIDENCE_FRAMEWORK_VERSION = "0.1.0"
CERTIFICATION_EVIDENCE_PACKAGE_CONTRACT_VERSION = "1.0"
CERTIFICATION_PROVENANCE_CONTRACT_VERSION = "1.0"
CERTIFICATION_SIGNATURE_CONTRACT_VERSION = "1.0"
CERTIFICATION_TRUST_POLICY_CONTRACT_VERSION = "1.0"
CERTIFICATION_FRESHNESS_POLICY_CONTRACT_VERSION = "1.0"
CERTIFICATION_IMPORT_CONTRACT_VERSION = "1.0"
CERTIFICATION_REVIEW_CONTRACT_VERSION = "1.0"
CERTIFICATION_COMPARISON_CONTRACT_VERSION = "1.0"


__all__ = [
    "CERTIFICATION_COMPARISON_CONTRACT_VERSION",
    "CERTIFICATION_EVIDENCE_FRAMEWORK_VERSION",
    "CERTIFICATION_EVIDENCE_PACKAGE_CONTRACT_VERSION",
    "CERTIFICATION_FRESHNESS_POLICY_CONTRACT_VERSION",
    "CERTIFICATION_IMPORT_CONTRACT_VERSION",
    "CERTIFICATION_PROVENANCE_CONTRACT_VERSION",
    "CERTIFICATION_REVIEW_CONTRACT_VERSION",
    "CERTIFICATION_SIGNATURE_CONTRACT_VERSION",
    "CERTIFICATION_TRUST_POLICY_CONTRACT_VERSION",
]
