"""Staging analytics certification contract versions."""

STAGING_ANALYTICS_CERTIFICATION_VERSION = "0.1.0"
STAGING_ANALYTICS_PROFILE_CONTRACT_VERSION = "1.0"
STAGING_ANALYTICS_RUN_CONTRACT_VERSION = "1.0"
STAGING_BROWSER_EVIDENCE_CONTRACT_VERSION = "1.0"
PROVIDER_OBSERVED_RECONCILIATION_CONTRACT_VERSION = "1.0"
STAGING_CERTIFICATION_REPORT_CONTRACT_VERSION = "1.0"
INSTRUMENTATION_SUPPORT_BUNDLE_CONTRACT_VERSION = "1.0"

__all__ = [
    "INSTRUMENTATION_SUPPORT_BUNDLE_CONTRACT_VERSION",
    "PROVIDER_OBSERVED_RECONCILIATION_CONTRACT_VERSION",
    "STAGING_ANALYTICS_CERTIFICATION_VERSION",
    "STAGING_ANALYTICS_PROFILE_CONTRACT_VERSION",
    "STAGING_ANALYTICS_RUN_CONTRACT_VERSION",
    "STAGING_BROWSER_EVIDENCE_CONTRACT_VERSION",
    "STAGING_CERTIFICATION_REPORT_CONTRACT_VERSION",
]
