"""Stable Plugin SDK v1 contract versions."""

PLUGIN_SDK_VERSION = "1.0.0"
CHANNEL_PLUGIN_SDK_CONTRACT_VERSION = "1.0"
PROVIDER_PLUGIN_SDK_CONTRACT_VERSION = "1.0"
MEDIA_PLUGIN_SDK_CONTRACT_VERSION = "1.0"
PLUGIN_MANIFEST_SCHEMA_VERSION = "1.0"
PLUGIN_TESTKIT_CONTRACT_VERSION = "1.0"
PLUGIN_FIXTURE_CONTRACT_VERSION = "1.0"
PLUGIN_DOCTOR_CONTRACT_VERSION = "1.0"

__all__ = [
    "PLUGIN_SDK_VERSION",
    "CHANNEL_PLUGIN_SDK_CONTRACT_VERSION",
    "PROVIDER_PLUGIN_SDK_CONTRACT_VERSION",
    "MEDIA_PLUGIN_SDK_CONTRACT_VERSION",
    "PLUGIN_MANIFEST_SCHEMA_VERSION",
    "PLUGIN_TESTKIT_CONTRACT_VERSION",
    "PLUGIN_FIXTURE_CONTRACT_VERSION",
    "PLUGIN_DOCTOR_CONTRACT_VERSION",
]
