"""Website analytics instrumentation framework."""

from .contracts import (
    PLAUSIBLE_BROWSER_BRIDGE_VERSION,
    WEBSITE_ANALYTICS_INSTRUMENTATION_VERSION,
    WEBSITE_CONSENT_MODE_CONTRACT_VERSION,
    WEBSITE_EVENT_ENVELOPE_CONTRACT_VERSION,
    WEBSITE_INSTRUMENTATION_MANIFEST_CONTRACT_VERSION,
    WEBSITE_INSTRUMENTATION_PROFILE_CONTRACT_VERSION,
    WEBSITE_INSTRUMENTATION_QUALITY_CONTRACT_VERSION,
    WEBSITE_INSTRUMENTATION_VERIFICATION_CONTRACT_VERSION,
    WEBSITE_PAGE_CONTEXT_CONTRACT_VERSION,
)
from .service import WebsiteInstrumentationService

__all__ = [
    "PLAUSIBLE_BROWSER_BRIDGE_VERSION",
    "WEBSITE_ANALYTICS_INSTRUMENTATION_VERSION",
    "WEBSITE_CONSENT_MODE_CONTRACT_VERSION",
    "WEBSITE_EVENT_ENVELOPE_CONTRACT_VERSION",
    "WEBSITE_INSTRUMENTATION_MANIFEST_CONTRACT_VERSION",
    "WEBSITE_INSTRUMENTATION_PROFILE_CONTRACT_VERSION",
    "WEBSITE_INSTRUMENTATION_QUALITY_CONTRACT_VERSION",
    "WEBSITE_INSTRUMENTATION_VERIFICATION_CONTRACT_VERSION",
    "WEBSITE_PAGE_CONTEXT_CONTRACT_VERSION",
    "WebsiteInstrumentationService",
]
