"""CI artifact import framework."""

from .contracts import (
    CI_ARTIFACT_IMPORT_CONTRACT_VERSION,
    CI_ARTIFACT_RETENTION_CONTRACT_VERSION,
    CI_ARTIFACT_SOURCE_CONTRACT_VERSION,
    CI_EVIDENCE_PROMOTION_CONTRACT_VERSION,
    CI_IMPORT_ATTESTATION_CONTRACT_VERSION,
    CI_IMPORT_AUDIT_TRAIL_CONTRACT_VERSION,
    CI_IMPORT_DRY_RUN_CONTRACT_VERSION,
    CI_IMPORT_OPERATOR_SESSION_CONTRACT_VERSION,
    CURRENT_COMMIT_READINESS_CONTRACT_VERSION,
    GITHUB_ACTIONS_ARTIFACT_SOURCE_VERSION,
    GITHUB_CI_OPERATOR_FLOW_VERSION,
)
from .operator_flow import CiEvidenceOperatorService, CurrentCommitResolver
from .service import CiArtifactImportService
from .worker import CiArtifactImportWorker

__all__ = [
    "CI_ARTIFACT_IMPORT_CONTRACT_VERSION",
    "CI_ARTIFACT_RETENTION_CONTRACT_VERSION",
    "CI_ARTIFACT_SOURCE_CONTRACT_VERSION",
    "CI_IMPORT_ATTESTATION_CONTRACT_VERSION",
    "CI_IMPORT_AUDIT_TRAIL_CONTRACT_VERSION",
    "CI_IMPORT_DRY_RUN_CONTRACT_VERSION",
    "CI_IMPORT_OPERATOR_SESSION_CONTRACT_VERSION",
    "CI_EVIDENCE_PROMOTION_CONTRACT_VERSION",
    "CURRENT_COMMIT_READINESS_CONTRACT_VERSION",
    "CiArtifactImportService",
    "CiArtifactImportWorker",
    "CiEvidenceOperatorService",
    "CurrentCommitResolver",
    "GITHUB_ACTIONS_ARTIFACT_SOURCE_VERSION",
    "GITHUB_CI_OPERATOR_FLOW_VERSION",
]
