"""Contract versions for CI artifact import."""

CI_ARTIFACT_SOURCE_CONTRACT_VERSION = "1.0"
CI_ARTIFACT_IMPORT_CONTRACT_VERSION = "1.0"
CI_IMPORT_ATTESTATION_CONTRACT_VERSION = "1.0"
CI_ARTIFACT_RETENTION_CONTRACT_VERSION = "1.0"
GITHUB_ACTIONS_ARTIFACT_SOURCE_VERSION = "0.1.0"
GITHUB_CI_OPERATOR_FLOW_VERSION = "0.1.0"
CI_IMPORT_OPERATOR_SESSION_CONTRACT_VERSION = "1.0"
CI_IMPORT_DRY_RUN_CONTRACT_VERSION = "1.0"
CI_EVIDENCE_PROMOTION_CONTRACT_VERSION = "1.0"
CI_IMPORT_AUDIT_TRAIL_CONTRACT_VERSION = "1.0"
CURRENT_COMMIT_READINESS_CONTRACT_VERSION = "1.0"

__all__ = [
    "CI_ARTIFACT_IMPORT_CONTRACT_VERSION",
    "CI_ARTIFACT_RETENTION_CONTRACT_VERSION",
    "CI_ARTIFACT_SOURCE_CONTRACT_VERSION",
    "CI_IMPORT_ATTESTATION_CONTRACT_VERSION",
    "GITHUB_ACTIONS_ARTIFACT_SOURCE_VERSION",
    "GITHUB_CI_OPERATOR_FLOW_VERSION",
    "CI_IMPORT_OPERATOR_SESSION_CONTRACT_VERSION",
    "CI_IMPORT_DRY_RUN_CONTRACT_VERSION",
    "CI_EVIDENCE_PROMOTION_CONTRACT_VERSION",
    "CI_IMPORT_AUDIT_TRAIL_CONTRACT_VERSION",
    "CURRENT_COMMIT_READINESS_CONTRACT_VERSION",
]
