"""Plugin Host Framework contract versions."""

PLUGIN_HOST_FRAMEWORK_VERSION = "0.1.0"
PLUGIN_HOST_PROTOCOL_VERSION = "1.0"
PLUGIN_HOST_HANDSHAKE_CONTRACT_VERSION = "1.0"
PLUGIN_HOST_LIFECYCLE_CONTRACT_VERSION = "1.0"
PLUGIN_HOST_CALLBACK_CONTRACT_VERSION = "1.0"
PLUGIN_HOST_RESOURCE_POLICY_CONTRACT_VERSION = "1.0"
PLUGIN_HOST_ENVIRONMENT_CONTRACT_VERSION = "1.0"
PLUGIN_HOST_CRASH_POLICY_CONTRACT_VERSION = "1.0"

__all__ = [
    "PLUGIN_HOST_CALLBACK_CONTRACT_VERSION",
    "PLUGIN_HOST_CRASH_POLICY_CONTRACT_VERSION",
    "PLUGIN_HOST_ENVIRONMENT_CONTRACT_VERSION",
    "PLUGIN_HOST_FRAMEWORK_VERSION",
    "PLUGIN_HOST_HANDSHAKE_CONTRACT_VERSION",
    "PLUGIN_HOST_LIFECYCLE_CONTRACT_VERSION",
    "PLUGIN_HOST_PROTOCOL_VERSION",
    "PLUGIN_HOST_RESOURCE_POLICY_CONTRACT_VERSION",
]
