"""Plugin Sandbox Framework contract versions."""

PLUGIN_SANDBOX_FRAMEWORK_VERSION = "0.1.0"
PLUGIN_SANDBOX_POLICY_CONTRACT_VERSION = "1.0"
PLUGIN_SANDBOX_PLAN_CONTRACT_VERSION = "1.0"
PLUGIN_SANDBOX_ATTESTATION_CONTRACT_VERSION = "1.0"
PLUGIN_SANDBOX_FILESYSTEM_CONTRACT_VERSION = "1.0"
PLUGIN_SANDBOX_NETWORK_CONTRACT_VERSION = "1.0"
PLUGIN_SANDBOX_SYSCALL_CONTRACT_VERSION = "1.0"
PLUGIN_SANDBOX_VIOLATION_CONTRACT_VERSION = "1.0"
PLUGIN_SANDBOX_PLATFORM_CONTRACT_VERSION = "1.0"

__all__ = [
    "PLUGIN_SANDBOX_ATTESTATION_CONTRACT_VERSION",
    "PLUGIN_SANDBOX_FILESYSTEM_CONTRACT_VERSION",
    "PLUGIN_SANDBOX_FRAMEWORK_VERSION",
    "PLUGIN_SANDBOX_NETWORK_CONTRACT_VERSION",
    "PLUGIN_SANDBOX_PLAN_CONTRACT_VERSION",
    "PLUGIN_SANDBOX_PLATFORM_CONTRACT_VERSION",
    "PLUGIN_SANDBOX_POLICY_CONTRACT_VERSION",
    "PLUGIN_SANDBOX_SYSCALL_CONTRACT_VERSION",
    "PLUGIN_SANDBOX_VIOLATION_CONTRACT_VERSION",
]
