"""Deterministic Markdown Website fixture catalog."""

SCENARIOS = (
    "healthy_generic_yaml_site",
    "hugo_style_contentroot",
    "astro_style_contentroot",
    "mdx_profile",
    "dirty_worktree_without_overlap",
    "dirty_worktree_with_overlap",
    "slug_collision",
    "media_collision",
    "remote_divergence",
    "push_success",
    "push_response_lost",
    "deployment_pending",
    "deployment_verified",
    "canonical_mismatch",
    "revision_marker_mismatch",
    "external_file_drift",
    "update",
    "delete_unpublish",
    "draft_unpublish",
    "dependency_success",
    "dependency_pending",
    "dependency_failure",
    "dependency_cycle",
    "website_metrics",
    "social_attribution",
    "conversion_attribution",
)
