"""Managed secret framework contracts."""

MANAGED_SECRET_FRAMEWORK_VERSION = "0.1.0"
SECRET_REFERENCE_CONTRACT_VERSION = "1.0"
SECRET_BACKEND_CONTRACT_VERSION = "1.0"
SECRET_LEASE_CONTRACT_VERSION = "1.0"
SECRET_APPROVAL_CONTRACT_VERSION = "1.0"
SECRET_ROTATION_CONTRACT_VERSION = "1.0"
SECRET_HEALTH_CONTRACT_VERSION = "1.0"
OPERATOR_ROLE_CONTRACT_VERSION = "1.0"
OPERATOR_APPROVAL_CONTRACT_VERSION = "1.0"
LOCAL_ENCRYPTED_SECRET_BACKEND_VERSION = "0.1.0"


__all__ = [
    "LOCAL_ENCRYPTED_SECRET_BACKEND_VERSION",
    "MANAGED_SECRET_FRAMEWORK_VERSION",
    "OPERATOR_APPROVAL_CONTRACT_VERSION",
    "OPERATOR_ROLE_CONTRACT_VERSION",
    "SECRET_APPROVAL_CONTRACT_VERSION",
    "SECRET_BACKEND_CONTRACT_VERSION",
    "SECRET_HEALTH_CONTRACT_VERSION",
    "SECRET_LEASE_CONTRACT_VERSION",
    "SECRET_REFERENCE_CONTRACT_VERSION",
    "SECRET_ROTATION_CONTRACT_VERSION",
]
