from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol

from .models import BrowserArtifact, BrowserSnapshot, BrowserTarget


class BrowserSession(Protocol):
    @property
    def session_id(self) -> str: ...

    def navigate(self, url: str) -> BrowserSnapshot: ...

    def snapshot(self) -> BrowserSnapshot: ...

    def current_url(self) -> str: ...

    def title(self) -> str: ...

    def element_exists(self, target: BrowserTarget, *, timeout_millis: int = 0) -> bool: ...

    def text_content(self, target: BrowserTarget) -> str: ...

    def attribute(self, target: BrowserTarget, name: str) -> str: ...

    def wait_for(self, target: BrowserTarget, *, state: str = "visible", timeout_millis: int = 1000) -> bool: ...

    def wait_for_timeout(self, millis: int) -> None: ...

    def reload(self) -> BrowserSnapshot: ...

    def go_back(self) -> BrowserSnapshot: ...

    def keyboard_press(self, key: str) -> None: ...

    def keyboard_insert_text(self, text: str) -> None: ...

    def click(self, target: BrowserTarget) -> None: ...

    def fill(self, target: BrowserTarget, value: str) -> None: ...

    def upload(self, target: BrowserTarget, path: Path) -> None: ...

    def evaluate(self, script: str, arg: Any | None = None) -> Any: ...

    def screenshot(self, *, full_page: bool = True) -> BrowserArtifact: ...

    def close(self) -> None: ...
